name: air-quality-forecasting
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow=2.6
  - jupyter
  - pyyaml
  - tqdm
  - statsmodels
  - xgboost
  - lightgbm
  - hyperopt
  - pip:
      - optuna
      - mlflow